### ISSUE TITLE
Fail on Twitter callback

### ISSUE THREAD

**Issue by c-cesar** [idno/Twitter#12]
When registring the user I get a empty page on callback with the URL http://mysite.com/twitter/callback?oauth_token=[TOKEN]&oauth_verifier=[VERIFIER] and cant finish the authentication. 
I don't have a error on apache log, but entry on acces log.

**Comment by korayal** [comment]
Have you managed to overcome this issue? 

I also have the same problem now.

**Comment by cochise** [comment]
Some time afer this attempt I installed again and all things worked, as said in https://github.com/idno/Facebook/issues/13
The difference is in my first instalation I used a subdomain and now I'm using a main level domain. If your installation also isin a subdomain we can confirm the bug.

**Comment by benwerd** [comment]
That's concerning. To confirm, do you mean subdomain or subdirectory?
Subdomains shouldn't make any difference.

On Sat, Mar 21, 2015 at 9:42 AM, Cochise César <notifications@github.com>
wrote:

> Some time afer this attempt I installed again and all things worked, as
> said in idno/Facebook#13 <https://github.com/idno/Facebook/issues/13>
> The difference is in my first instalation I used a subdomain and now I'm
> using a main level domain. If your installation also isin a subdomain we
> can confirm the bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Twitter/issues/12#issuecomment-84388882>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by korayal** [comment]
Apache/2.4.12
PHP 5.4.38
Mysql 5.6.23
(Running on a cpanel account)

(I was also able to connect LinkedIN and Foursquare accounts [Facebook connect also seemed to not work.] But neither of them are displayed as an option during posting)

**Comment by mapkyca** [comment]
Old bug, going to close with a #worksforme since this has clearly been fixed a looong time ago
