### ISSUE TITLE
no respect of https

### ISSUE THREAD

**Issue by pierreozoux** [idno/Twitter#16]
It looks like the plugin is unable to recognize that the site is using https.

On the call back url, I have a url without https.
When I post, I have a warning from firefox.
After inspection of the source code: `action="http://microblog.pierre-o.fr/admin/twitter/"`

**Comment by benwerd** [comment]
Is this using the very latest version of the plugin? This change should have been made last week.

**Comment by pierreozoux** [comment]
I used the plugin version 0.1 that is shipped with known version 0.6.5.
Is it the last version?

**Comment by benwerd** [comment]
We'll make a new release soon, containing new plugins. In the meantime, you can grab the latest at https://github.com/idno/facebook
