### ISSUE TITLE
Fail to post on twitter

### ISSUE THREAD

**Issue by pierreozoux** [idno/Twitter#19]
I get the following error while posting to twitter:
```
Fatal Error: /app/IdnoPlugins/Twitter/Main.php:148 - "Call to undefined method IdnoPlugins\Text\Entry::getSyndicationURL()", on page microblog.pierre-o.fr/entry/edit
```

This happens for post, and not status.

Tell me if there need more to help debug.

**Comment by benwerd** [comment]
You need to upgrade your core Known to the latest in git. We introduced the getSyndicationURL method recently.

**Comment by pierreozoux** [comment]
Ok, thanks and sorry :/
It is because of that, I was sure to run the latest version... Next time, I'll check, I promise :)
https://github.com/idno/Known/issues/859
