### ISSUE TITLE
Call to undefined method?

### ISSUE THREAD

**Issue by chrisaldrich** [idno/Twitter#20]
Fatal Error: /homepages/32/d491429024/htdocs/idno/IdnoPlugins/Twitter/Main.php:148 - "Call to undefined method IdnoPlugins\Text\Entry::getSyndicationURL()", on page stream.boffosocko.com/entry/edit

I had this error pop up right after upgrading to 0.7.7.1 and using the most recent Twitter plugin commit https://github.com/idno/Twitter/commit/3ec783227ce403cf84cc89fd1a203cc2fe69316a 

It occurred when publishing a post. Prior to this, I had done one or two status updates with no problem.  I rolled back to the Twitter plugin that came with 0.7.6 and ran a few more test posts and status updates with no issues. Is it possible the recent function change on line 148 would have problems with posts? Or conflicts with the core?

**Comment by benwerd** [comment]
The core needs to be upgraded to the git latest. A new installer should be produced by the end of the month.

**Comment by pierreozoux** [comment]
Yes can't wait :) https://github.com/IndiePaaS/IndiePaaS/commit/9753d7ad097334cea0ee15940647fa1f9a41d0e7

**Comment by pierreozoux** [comment]
Danke! https://github.com/IndiePaaS/IndiePaaS/commit/d5f8fc2a8929d441f477f322790ab0eb3c3722c6
(You can close)
