### ISSUE TITLE
photo aren't posted to twitter

### ISSUE THREAD

**Issue by danito** [idno/Twitter#24]
On my Known, photos aren't published on twitter (but it works for Facebook and for status and posts).
Any ideas?

**Comment by benwerd** [comment]
Twitter is very picky about photo sizes. It's possible that your Known
installation isn't correctly making thumbnails, and as a result photos are
being rejected from Twitter.

On Wed, Jun 10, 2015 at 9:58 AM, Daniel nix <notifications@github.com>
wrote:

> On my Known, photos aren't published on twitter (but it works for Facebook
> and for status and posts).
> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Twitter/issues/24>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by danito** [comment]
just checked the logs : 
PHP Notice:  Undefined index: mime_type in /var/www/virtual/nxd4n/html/IdnoPlugins/Twitter/Main.php on line 250, referer: http://nxd4n.nixekinder.be/
[Mon Jun 22 14:53:36 2015] [warn] [client ] mod_fcgid: stderr: PHP Notice:  Undefined index: filename in /var/www/virtual/nxd4n/html/IdnoPlugins/Twitter/Main.php on line 250, referer: http://nxd4n.nixekinder.be/
[Mon Jun 22 14:53:36 2015] [warn] [client ] mod_fcgid: stderr: Known (nxd4n.nixekinder.be): INFO - Nothing was posted to Twitter: stdClass::__set_state(array(, referer: http://nxd4n.nixekinder.be/

correct with #25

**Comment by KashCorp** [comment]
Hi, 
I have the same issue about photo not being post on twitter. 

There is the part my error log from nginx

`2015/06/22 21:54:28 [warn] 2572#0: *7524 a client request body is buffered to a temporary file /etc/nginx/client_body_temp/0000000013, client: 109.128.250.169, server: kash.space, request: "POST /photo/edit HTTP/1.1", host: "kash.space", referrer: "https://kash.space/content/all/"
2015/06/22 21:54:37 [error] 2572#0: *7524 FastCGI sent in stderr: "PHP message: Didn't get slug
PHP message: Setting resilient slug
PHP message: Set resilient slug
PHP message: Didn't get slug
PHP message: Setting resilient slug
PHP message: Set resilient slug
PHP message: Known (kash.space): INFO - Pinging https://withknown.superfeedr.com/ with data hub.mode=publish&hub.url=https%3A%2F%2Fkash.space%2F,https%3A%2F%2Fkash.space%2F%3F_t%3Drss,https%3A%2F%2Fkash.space%2Fcontent%2Fphotos%2F,https%3A%2F%2Fkash.space%2Fcontent%2Fphotos%2F%3F_t%3Drss,https%3A%2F%2Fkash.space%2Fcontent%2Fall%2F,https%3A%2F%2Fkash.space%2Fcontent%2Fall%2F%3F_t%3Drss 5
PHP message: Known (kash.space): DEBUG - {"_id":"20365647a032898deeff206106f21f8b","url":"https:\/\/kash.space\/file\/20365647a032898deeff206106f21f8b\/388f8fe5a6ed282b18b2356c7b2dadcf.jpg","mime-type":"image\/jpeg","length":2148733} 5 [/var/www/kash.space/public/Idno/Entities/File.php:324]
PHP message: PHP Notice:  Undefined index: mime_type in /var/www/kash.space/public/IdnoPlugins/Twitter/Main.php on line 246
PHP message: PHP Notice:  Undefined index: filename in /var/www/kash.space/public/IdnoPlugins/Twitter/Main.php on line 246
PHP message: Known (kash.space): INFO - Nothing was posted to Twitter: stdClass::__set_state(array(
   'errors' =>
  array (
    0 =>
    stdClass::__set_state(array(
       'code' => 189,
       'message' => 'Error creating status.',
    )),
  ),
)) 5" while reading response header from upstream, client: 109.128.250.169, server: kash.space, request: "POST /photo/edit HTTP/1.1", upstream: "fastcgi://unix:/var/www/kash.space/php.sock:", host: "kash.space", referrer: "https://kash.space/content/all/"
`

I think your are right Ben it is about max size. If you know how to set the good parameters to create thumbnails, fell free to explain me 'cause I have no clue ;-)

Thank you.

**Comment by danito** [comment]
see also my request #25 which corrects the undefined index error. If you correct mime_type to mime-type you'll get an error for missing index filename.
If I understand well, update_with_media needs the filename without the path, but this info is missing in the $attachment array. 
statuses/update_with_media is deprecated anyway and one should first upload a message and get an media_id back and then post a status with this media_id.
So I'm not sure that the size of the image is the problem as I can upload a picture when using media/uploads and I get an id back. But then the status is not updated with statuses/update.json (wrong api error message).
I'm still looking for what's not correct.

**Comment by danito** [comment]
fixed with #26 from https://github.com/danito/Twitter

**Comment by kylewm** [comment]
Sounds like this can be closed

**Comment by herbsmn** [comment]
I agree with @kylewm. This one can be closed.

**Comment by danito** [comment]
closing
