### ISSUE TITLE
Can't Enable Plugin

### ISSUE THREAD

**Issue by hank** [idno/Twitter#28]
I have this plugin (the trunk) checked out in IdnoPlugins with all the other plugins.  When I click enable, the page refreshes and the top says "The plugin was installed.", but it still has the Enable button visible.  No matter how many times I click it, it's the same result.  There aren't any messages in my http error log that seem relevant.  Please let me know how to debug this issue.

**Comment by hank** [comment]
Turns out I had it in antiplugins.  Perhaps Idno should let you know if you attempt to enable a plugin in that list, or disable the Enable button entirely with something like "Blocked".

**Comment by benwerd** [comment]
Thanks for the heads up - it shouldn't show in the list at all.

On Wed, Sep 23, 2015 at 7:46 PM, hank <notifications@github.com> wrote:

> Turns out I had it in antiplugins. Perhaps Idno should let you know if you
> attempt to enable a plugin in that list, or disable the Enable button
> entirely with something like "Blocked".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Twitter/issues/28#issuecomment-142787634>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
