### ISSUE TITLE
Failed to enable Twitter

### ISSUE THREAD

**Issue by drikkes** [idno/Twitter#31]
I dropped the Twitter folder onto my server, got to the Known settings, and this message appears right after I click the "Enable" button.
Fatal Error: /var/www/virtual/drikkes/html/gold/IdnoPlugins/Twitter/Main.php:31 - "Call to undefined method Idno\Core\Idno::site()", on page drikk.es/gold/admin/plugins/
Hat to delete the whole folder, otherwise I got the message on every site on the admin panel.

**Comment by benwerd** [comment]
You need to update to the latest Known code. A new release will be made by
the end of December.

On Tuesday, December 22, 2015, -drik S. <notifications@github.com> wrote:

> I dropped the Twitter folder onto my server, got to the Known settings,
> and this message appears right after I click the "Enable" button
> Fatal Error:
> /var/www/virtual/drikkes/html/gold/IdnoPlugins/Twitter/Mainphp:31 - "Call
> to undefined method Idno\Core\Idno::site()", on page
> drikkes/gold/admin/plugins/
> Hat to delete the whole folder, otherwise I got the message on every site
> on the admin panel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Twitter/issues/31>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by drikkes** [comment]
Thanks for the answer. 
So I wait for version 0.8.6 or 0.9...?

**Comment by benwerd** [comment]
You could also just grab the main .zip from the GitHub repo and overwrite your Idno, Themes, js and css folders.

**Comment by drikkes** [comment]
Works for me. http://drikk.es Thanks!

**Comment by jgmac1106** [comment]
I just installed the latest .zip (unless repo linked from withknown.com isn't latest  from the repo and I am also running into the enable button problem. I will try and copy what @drikkes did.

**Comment by askans** [comment]
I use 0.91 - self-hosted - on a shared web space - and still cannot enable Twitter plugin. Any suggestions?

**Comment by rikmendes** [comment]
make sure that you have the **Twitter** folder in the root of your //IdnoPlugins/ folder ?
(it should not be **KnownTwitter** for example (the git root file if you use git to pull plugins)

it should be straightforward if you can see  
![screenshot_98](https://cloud.githubusercontent.com/assets/12155003/14032320/3e3d2096-f212-11e5-8702-6756f5afb9b5.png)

**Comment by rikmendes** [comment]
Do you see the Twitter plugin in the list ?
![screenshot_100](https://cloud.githubusercontent.com/assets/12155003/14032465/5fa57098-f213-11e5-8647-a56c5c28f2ac.png)
![screenshot_99](https://cloud.githubusercontent.com/assets/12155003/14032467/63f65374-f213-11e5-81bf-1367dc689d96.png)

**Comment by askans** [comment]
This was exactly the point: my folder was called "Twitter-master"  and I renamed it to "Twitter", then it was possible to proceed. Thanks a lot
