### ISSUE TITLE
Indieweb Twitter threading not working

### ISSUE THREAD

**Issue by benwerd** [idno/Twitter#42]
If I reply to a user's Known site and also syndicate to Twitter, my syndicated Twitter post will no longer be threaded with the original post's syndicated copy.

**Comment by kylewm** [comment]
hmm, seems to be working for me https://twitter.com/kylewmahan/status/700122134102695937

is it the issue of not including the @-username on the posse copy (it's not autofilled since you aren't replying directly to twitter)?

**Comment by benwerd** [comment]
It's not that. It's this adjacent issue:

* Ben is an idiot

User attempted to test plugin using really old version without updating site. User will be punished.
