### ISSUE TITLE
Wrong Callback-URL from backend

### ISSUE THREAD

**Issue by wobintosh2** [idno/Twitter#44]
Backend (my.domain.de/admin/twitter/) tells me I should set the callback URL in Twitter Apps to "https://my.domain.de/twitter/callback/".

Twitter is saying me "The client application failed validation: Not a valid URL format." 

Don't know if this is a problem with the plugin/Known or with twitter.

**Comment by tinokremer** [comment]
I take it you changed my.domain.de to the actual domain? Make sure there is no other stuff in the inputbox. I just created a new application:

![image](https://cloud.githubusercontent.com/assets/546983/13905698/9bf8434e-eec7-11e5-9879-ccdd15c2fc30.png)

That seems to work just fine:
![image](https://cloud.githubusercontent.com/assets/546983/13905700/ad19aa28-eec7-11e5-94de-cc147ae41c1b.png)

If you feel everything is correct, perhaps you could provide a screenshot so I can try to mimic your settings?

**Comment by wobintosh2** [comment]
Well, it seems that this was a problem at twitter - now it works fine with the URL given by known. 
Nevertheless, many thanks!
