### ISSUE TITLE
Can't connect twitter after upgrading to 0.9.9-a

### ISSUE THREAD

**Issue by voss** [idno/Twitter#58]
Hi there,

Updated recently to 0.9.9-a by cloning it from the github rep. Afterwards, I installed the twitter plugin from idno/Twitter by cloning the rep as well. I've tried disabling and reenabling the twitter plugin, and I've also tried to refresh my API key and client secret for the app I've made on apps.twitter.com to post on twitter on my behalf, but so far this hasn't worked out.

The behaviour I'm seeing is, that when I go to the /account/twitter url on my site, I see the "Connect Twitter" button. When I click it, I return to the same page, still with the button saying "Connect Twitter". If I try to make a new post, I don't get the Twitter button on the post either. Is there a way to reset the Twitter connection, or something I can check for to investigate what the issue might be?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Twitter/issues/58" class="u-in-reply-to"></a>Anything in your logs?

**Comment by voss** [comment]
Hi @mapkyca, thanks for your reply!

I checked my logs, and in the access.log for apache, I get the following sequence when trying to connect.

`[15/Oct/2018:05:32:05 -0700] "GET /twitter/auth HTTP/1.1" 302 4377 "https://domain.example/account/twitter/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.54 Safari/537.36" 
[15/Oct/2018:05:32:05 -0700] "GET /account/twitter/ HTTP/1.1" 200 18336 "https://domain.example/account/twitter/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.54 Safari/537.36" 
[15/Oct/2018:05:32:05 -0700] "GET /styles/site/ HTTP/1.1" 200 1735 "https://domain.example/account/twitter/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.54 Safari/537.36" 
[15/Oct/2018:05:32:06 -0700] "GET /chrome/manifest.json HTTP/1.1" 200 5734 "https://domain.example/account/twitter/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.54 Safari/537.36" 
[15/Oct/2018:05:32:07 -0700] "GET /service-worker.min.js HTTP/1.1" 200 1228 "https://domain.example/service-worker.min.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.54 Safari/537.36"`

I checked error.log, but I don't see any lines written to it, when hitting the "connect twitter" button.

I'm hosted on dreamhost shared hosting, and I'm on PHP 7.0 FastCGI.

I know it's not easy troubleshooting these things from a distance. I was on Known 0.9.9 (release version) before, and the server was on PHP 5.6 FastCGI. Twitter was working then, and I only came across this issue after I updated the server to PHP 7.0 FastCGI, and Known to the 0.9.9-a master from Github.''

Not sure any of the above helps (:

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Twitter/issues/58#issuecomment-429839943" class="u-in-reply-to"></a>Hmm...

I haven't been able to replicate - I can connect to twitter (latest build of the plugin, and latest known from github).

Server is PHP 7 / Apache2.

When you hit the connect to twitter button, do you get forwarded to twitter and are asked to authorise the app there?

**Comment by benwerd** [comment]
This is going to sound dumb, but try clearing your Known-side cookies.

**Comment by voss** [comment]
Hi @benwerd, thanks for the suggestion! I did nuke the site data, including all cookies for my Known instance, but let me give it another go and let you know.

**Comment by benwerd** [comment]
The reason is, I've seen this sometimes happen with misshapen oauth data. Also: I wonder if this is a browser issue? Safari in particular handles cookie setting on redirect differently to everyone else. If so, that's definitely a bug that needs to be fixed.

**Comment by voss** [comment]
Good point. I tried in both an incognito window in Chrome just now, and also in a private session in Firefox (latest release), and it's the same issue. It just reloads the page with the Known account settings for Twitter. I'll try removing the twitter plugin, and adding it again, and see if that helps.

**Comment by voss** [comment]
I deleted the Twitter folder from IdnoPlugins, and cloned it again from github. Same result. I have I feeling I did something to break it, since it worked fine before I upgraded to 0.9.9-a, and @mapkyca isn't able to reproduce it. Might try to clone Known again, on another domain, to see if I can make it work there.

**Comment by cdn** [comment]
Assuming that there are credentials (token/secret) on https://domain.example/admin/twitter/, otherwise such submission loops are quite likely, if one is impatient and forgets that side of the setup?

**Comment by voss** [comment]
@cdn got my API secrets and tokens in there. I also regenerated the token and secret just in case there was something wrong there:

![twitter_api_secrets](https://user-images.githubusercontent.com/10601/47007376-fb06e000-d12f-11e8-8069-1a6fce6a2633.jpg)

Let me try to setup Known on another domain this coming weekend and see if I'm able to reproduce it there.

**Comment by voss** [comment]
Update on this.

Cloned 0.9.9-a onto another domain, also hosted on dreamhost. Ran the warmup, where I'm told the installer is not able to tell if mod_rewrite is enabled on the domain, which it is by [default on all dreamhost servers](https://help.dreamhost.com/hc/en-us/articles/217141627-Supported-and-unsupported-technologies). Because of this, the warmup actually goes in an endless loop, and never finishes, but I'll file a separate issue for this against Known.

I handwrote my config.ini as a result of the warmup loop, and then cloned the Twitter plugin into the IdnoPlugin, supplied the consumer key and consumer secret in the settings for the plugin in Known, went to the setup page, clicked "Connect Twitter", and the same thing happens. Page reloads, no errors in the apache error.log.

Next step I'll do, is to install the release 0.9.9 version of Known, and try the same steps and see if that works.

**Comment by voss** [comment]
@cdn thanks for that extra detail.

I now installed 0.9.9, and cloned the master branch of the twitter plugin. I now end on a page that looks like this when I try to configure the twitter plugin on /admin/twitter:

![screenshot 2018-10-20 at 14 40 43](https://user-images.githubusercontent.com/10601/47256324-2b26e980-d476-11e8-8fc5-9b145edbae21.png)

The error message on the page says:

> Something went wrong.
> Call to undefined method Idno\Core\Language::_()
> Click here to try again, or click here to go back to the homepage.

Here's what git status gives on the Twitter plugin folder that I just cloned:
`$ Twitter git status`
`On branch master`
`Your branch is up-to-date with 'origin/master'.`
`nothing to commit, working directory clean`

Not sure entirely what I can do to make Twitter work again on a shared dreamhost setup. @cdn are you on Dreamhost as well?

I guess downgrading to 0.9.9 again, and trying to install one of the older commits to the Twitter plugin could be one path.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Twitter/issues/58#issuecomment-431580367" class="u-in-reply-to"></a>It looks like it's complaining because of the i18n functions, which are missing from the older 0.9.9 build. That build, btw, is over a year old... I suggest tracking github where you can, or using one of my unofficial packages (https://www.marcus-povey.co.uk/known) if you don't like tracking git...

**Comment by cdn** [comment]
@voss as @benwerd or @mapkyca would likely tell you 0.9.9 doesn’t have language handling functions, they’re a very recent addition to the Twitter plug–in by @mapkyca.

You might find a 0.9.9 + commit that adds them; or go straight to a recent 0.9.9-a one.
Or rewind Twitter to before they were added?

No, I’m not on Dreamhost, playing with Known on Raspbian (Raspberry Pi 3B).

**Comment by voss** [comment]
@mapkyca I am tracking git, or, at least that's what I wanted to do when I broke the twitter setup (: thanks for the link to your unofficial packages, I might do that instead of tracking git. 

So what I have right now, is the 0.9.9-a cloned from github. I did this to be able to just update from master branch using git on shared hosting provider, so it would be easier to roll updates on my install.

But the combination of using the master branch of Known, and the master branch of the Twitter plugin, doesn't seem to work on Dreamhost. Unfortunately.

@cdn got it, that makes sense. I would prefer using the git master branch, and then try to find a twitter version that worked with it on dreamhost. Time to do some experimenting I guess (:

**Comment by voss** [comment]
Well, I hope I don't wasted as much of anyone's time as my own looking at this, but I found the error, and of course, it was not related to Known at all, but rather to me being dim.

When I updated Known, I also updated PHP, and I **also** changed to https. Updating Known and PHP was the only thing I was thinking could have impacted it, but of course changing to https also had an impact, since I didn't update the URL in the Twitter app I had made to post on my behalf.

Adding https instead of http, solved the entire issue. Apologies for wasting peoples time on this.

Thanks all!

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Twitter/issues/58" class="u-in-reply-to"></a>Glad you got it sorted, thanks for letting us know about this!

**Comment by voss** [comment]
<a href="https://github.com/idno/Twitter/issues/58" class="u-in-reply-to"></a>Thanks for everyone's patience and help.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Twitter/issues/58" class="u-in-reply-to"></a>Standard procedure - replace everything except your configuration files and the Uploads directory.

For anyone who reads this - avoid using the "official" package on withknown.com, it's hopelessly out of date at this point. I think @benwerd is going to update the whole site, but he's a busy dude.

**Comment by raphaeljolivet** [comment]
Hi, I connot find a 0.9.9-a branch or tag on github.
Should I take the tip of "master" in order to have something up to date.

It's a pitty that a great software like Known does not have proper version / release management.

**Comment by davidmead** [comment]
OK @mapkyca.  I'll give that a go tonight.  

And by "your configuration files" do you mean the `.htaccess` and updated `config.ini` for the database connections? Or is there a folder that I shouldn't touch?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Twitter/issues/58" class="u-in-reply-to"></a>Those are they, and also leave the Uploads folder alone

**Comment by davidmead** [comment]
OK @mapkyca. Using your 0.9.9-a build and was able to connect to Twitter (still had the old app setup from 2015). Post showed up on Twitter fine.

**Comment by johanbove** [comment]
Joining in with this issue with the same Known versoin and latest Twitter plugin; having the same problem where clicking the "Connect Twitter" button navigates to /auth, which redirects to /account/twitter without notification that the connection works. The Twitter app callback now has to be https, so I have it at https://social.johanbove.info/twitter/callback
No CSP errors show up in the console and I don't have any other redirects in htacess.

**Comment by johanbove** [comment]
Update from my side; the redirect didn't work because I had a wrongly set the value for `url` in config.ini to `/`, while it should have been the full URL:
``
url = 'https://social.johanbove.info/'
host = 'social.johanbove.info'`
``

**Comment by jgmac1106** [comment]
Running into this issue now on every install I am currently doing. Will try what @johanbove fix

**Comment by jgmac1106** [comment]
Here is my config.ini

Feels like a timeout as it is trying to save the twitter credentials. I deleted the twitter plugin, reinstalled it, regenerated keys, and also looked to see how my htaccess or config.ini files are different (they are not).

```
filesystem = "local"
	path = /home/goifnetw/sadik.goifnetwork.org
	uploadpath = /home/goifnetw/sadik.goifnetwork.org/Uploads
```

**Comment by johanbove** [comment]
> Running into this issue now on every install I am currently doing. Will try what @johanbove fix

I wasn't able to fix this actually @jgmac1106 

Decided to drop this plugin and do manually Twitter publications using https://brid.gy instead. For the low volume of posts I want to share on Twitter, that was my quickest solution.

**Comment by johanbove** [comment]
So since I would still like the POSSE syndication links to Twitter, I decided to try again to install the plugin. I am getting as far as this URL (https://social.johanbove.info/account/twitter) with the following error message: "Your Twitter credentials could not be saved.". Which means the Twitter Callback.php page's code in the `get` function resolves to an HTML status code other than `200´` and it is unclear as to why my site can't get in touch with the Twitter API.

**Comment by johanbove** [comment]
Getting warmer to the cause of the code 0; from the TmhOAuth docs:
> If you are getting http code 0 responses inspect $tmhOAuth->response['error'] to see what the problem is. usually code 0 means cacert.pem cannot be found, and it can be fixed by putting cacert.pem in the location tmhOAuth is looking for it (indicated in the $tmhOAuth->response['error'] message), or by setting $tmhOAuth->config['curl_cainfo'] and $tmhOAuth->config['curl_capath'] values. setting $tmhOAuth->config['use_ssl'] to false IS NOT the way to solve this problem.

**Comment by johanbove** [comment]
So I fixed my issue by doing two things:

1. First upgraded the `/external/tmhOAuth/tmhOAuth.php` file to the latest version, which is 0.8.4
2. Update the cacert.pem file to the latest version (http://curl.haxx.se/ca/cacert.pem)

I've created an issue for the update here: #59
