### ISSUE TITLE
Replies aren't associated to tweet

### ISSUE THREAD

**Issue by mcg** [idno/Twitter#6]
Replying to posts end up creating a new post that aren't associated with the replied to tweet. 
To reproduce: Open tweet permalink in browser, hit Firefox service button or bookmarklet. Note that the tweet's permalink is used and the user is correctly @'d. Select "Twitter" and hit save. Post appears in Know and in Twitter, but as a new post and not associated with the tweet.

**Comment by mapkyca** [comment]
Old bug, going to close with a #worksforme since this has clearly been fixed a looong time ago
