### ISSUE TITLE
Can not set up plugin

### ISSUE THREAD

**Issue by nekr0z** [idno/Twitter#61]
When trying to set up the plugin (both plugin and known on current master branches) I consistently get:
```
Cannot access private property Idno\Core\Idno::$config
```
after providing the API credentials and pressing "save settings".

**Comment by mapkyca** [comment]
You using the latest version of the plugin?

**Comment by nekr0z** [comment]
> You using the latest version of the plugin?

Git master current.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Twitter/issues/61" class="u-in-reply-to"></a>Erp. Not tested as I'm on the road, but try the latest. Should work...

**Comment by nekr0z** [comment]
It does, thanks!
