### ISSUE TITLE
 Enabling this Plugin gives a 500 server error

### ISSUE THREAD

**Issue by Cambridgeport90** [idno/twitter#69]
I'm guessing the following is probably me. I'm running Known under Plesk running on top of centOS, and while the Composer extension is installed in the environment, only composer.json file it finds is the one under /ConsolePlugins/Import. I tried switching the application, too, and regardless of how many there are, that's the only one it finds. I'm getting the following details with an error. Any assistance would be great, even downloading the dependencies manually if needed would be fine with me, because I want to be able to have my POSSE to Twitter working. Error is as follows: 
Known experienced a problem with this page and couldn't continue.

Uncaught Error: Class 'Kylewm\Brevity\Brevity' not found in /home/cambridgeport90.org/httpdocs/IdnoPlugins/twitter/Main.php:16

The technical details are as follows:

Fatal Error: /home/cambridgeport90.org/httpdocs/IdnoPlugins/twitter/Main.php:16 - "Uncaught Error: Class 'Kylewm\Brevity\Brevity' not found in /home/cambridgeport90.org/httpdocs/IdnoPlugins/twitter/Main.php:16
Stack trace:
#0 /home/cambridgeport90.org/httpdocs/Idno/Common/Component.php(18): IdnoPlugins\Twitter\Main->init()
#1 /home/cambridgeport90.org/httpdocs/Idno/Core/Plugins.php(55): Idno\Common\Component->__construct()
#2 /home/cambridgeport90.org/httpdocs/Idno/Common/Component.php(18): Idno\Core\Plugins->init()
#3 /home/cambridgeport90.org/httpdocs/Idno/Core/Idno.php(255): Idno\Common\Component->__construct()
#4 /home/cambridgeport90.org/httpdocs/Idno/Common/Component.php(20): Idno\Core\Idno->registerPages()
#5 /home/cambridgeport90.org/httpdocs/Idno/Core/Idno.php(45): Idno\Common\Component->__construct()
#6 /home/cambridgeport90.org/httpdocs/Idno/start.php(126): Idno\Core\Idno->__construct()
#7 /home/cambridgeport90.org/httpdocs/index.php(30): require_once('/home/cambridge...')
#8 {main}
  thrown", on page www.cambridgeport90.org/

**Comment by mapkyca** [comment]
Not sure what's going on without more detail, but it does sound a lot like your install has been a little bit b0rked. 

If you're running from a checkout of GitHub you need to run composer yourself, but if you're running stuff through Plesk etc you might have better luck using one of the prepared binaries (e.g. https://www.marcus-povey.co.uk/known)
