### ISSUE TITLE
Class not defined on line 16 causes error 500

### ISSUE THREAD

**Issue by Cambridgeport90** [idno/Twitter#70]
I just recently installed this with the latest version of PHP, Known from GitHub, and I'm on Plesk. (had to download the files from the server and download the dependencies from my desktop). I figured at first that not having the /vender folder in there was causing a problem, but it doesn't seem to make a difference. I get:
Known experienced a problem with this page and couldn't continue.

Uncaught Error: Class 'Kylewm\Brevity\Brevity' not found in /var/www/vhosts/cambridgeport90.org/httpdocs/known/IdnoPlugins/twitter/Main.php:16

The technical details are as follows:

Fatal Error: /var/www/vhosts/cambridgeport90.org/httpdocs/known/IdnoPlugins/twitter/Main.php:16 - "Uncaught Error: Class 'Kylewm\Brevity\Brevity' not found in /var/www/vhosts/cambridgeport90.org/httpdocs/known/IdnoPlugins/twitter/Main.php:16
Stack trace:
#0 /var/www/vhosts/cambridgeport90.org/httpdocs/known/Idno/Common/Component.php(18): IdnoPlugins\Twitter\Main->init()
#1 /var/www/vhosts/cambridgeport90.org/httpdocs/known/Idno/Core/Plugins.php(55): Idno\Common\Component->__construct()
#2 /var/www/vhosts/cambridgeport90.org/httpdocs/known/Idno/Common/Component.php(18): Idno\Core\Plugins->init()
#3 /var/www/vhosts/cambridgeport90.org/httpdocs/known/Idno/Core/Idno.php(287): Idno\Common\Component->__construct()
#4 /var/www/vhosts/cambridgeport90.org/httpdocs/known/Idno/Common/Component.php(20): Idno\Core\Idno->registerPages()
#5 /var/www/vhosts/cambridgeport90.org/httpdocs/known/Idno/Core/Idno.php(46): Idno\Common\Component->__construct()
#6 /var/www/vhosts/cambridgeport90.org/httpdocs/known/Idno/start.php(126): Idno\Core\Idno->__construct()
#7 /var/www/vhosts/cambridgeport90.org/httpdocs/known/index.php(30):", on page cambridgeport90.org/known/index.php

Any assistance with this would be most appreciated; driving me nuts.

**Comment by mapkyca** [comment]
Copying the dependencies by hand isn't sufficient, since composer needs to rebuild the autoload files. So, you will need to rebuild those with a `composer dumpautoload`, or install the plugin directly with composer
