### ISSUE TITLE
Featrure: Have posts appear as Twitter Cards with a snippet of text or photo

### ISSUE THREAD

**Issue by elliottucker** [idno/Twitter#8]
https://dev.twitter.com/docs/cards

**Comment by finalcut** [comment]
It seems like this happens currently but it would be nice if this were an option.  The card that is inserted in my tweets is basically identical to the tweet.  Thus, I get this:

![image](https://cloud.githubusercontent.com/assets/108001/20841927/a137df64-b883-11e6-8461-a52a1a4a6b3c.png)


Which is obnoxious to say the least.

**Comment by rikmendes** [comment]
There is an option to change that, go to site configuration, scroll down and untick "Avatar as icon" you can also choose to add permalink or not to syndicated post. 
With that deactivated : if you want twitter card to display you will have to use the Post type kind and add an image o the post yourself for it to appear as a card. 
Le 2 déc. 2016 5:37 PM, Bill Rawlinson <notifications@github.com> a écrit :It seems like this happens currently but it would be nice if this were an option.  The card that is inserted in my tweets is basically identical to the tweet.  Thus, I get this:

Which is obnoxious to say the least.

**Comment by finalcut** [comment]
Thanks @rikmendes that did the trick
