### ISSUE TITLE
Bug connection to twitter account

### ISSUE THREAD

**Issue by avewrigley** [idno/Twitter#9]
I have installed this plugin on my idno server, but get the following bug:
1. click on "Settings" -> "Twitter"
2. click on "Click here to connect Twitter to your account"

"Known experienced a problem with this page and couldn't continue. The technical details are as follows:

Fatal Error: /var/www/idno/IdnoPlugins/Twitter/Main.php:239 - "Call to a member function request() on a non-object", on page idno.ave.wrigley.name/twitter/auth
We've logged this error and will make sure we take a look.

If you like, you can email us for more information."

**Comment by herbsmn** [comment]
I propose that this ticket get closed.
